[package]
name = "wcr"
version = "0.1.0"
edition = "2024"
license = "MIT"


[dependencies]
clap = "2.33"


[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
anyhow = "1.0.100"
pretty_assertions = "1.4.1"
